descriptor-schema-version: "2.0"
info:
  name: iperf
  version: "1.0"
  description: iPerf server for IOx deployment
app:
  cpuarch: x86_64
  type: docker
  resources:
    profile: c1.small
    network:
      - interface-name: eth0
        ports:
          - port: 5201
            protocol: tcp
          - port: 5201
            protocol: udp
startup:
  rootfs: rootfs.tar
  target: iperf3 -s
